language: python
os: linux
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - python ustvnow.py -u $USTVNOW_USERNAME -p $USTVNOW_PASSWORD -c $USTVNOW_CHANNEL -q highest -d
  - python -m flake8 ustvnow.py
